"use strict";
/**
 * PaymentGatewayService
 * Handles multi-method payment processing with graceful fallback when
 * third-party APIs (Stripe, PayPal, etc.) are unconfigured.
 *
 * Environment variables consumed (all optional, fallback to mock mode):
 *   STRIPE_SECRET_KEY        - Stripe secret key (sk_live_... or sk_test_...)
 *   PAYPAL_CLIENT_ID         - PayPal REST API client ID
 *   PAYPAL_CLIENT_SECRET     - PayPal REST API client secret
 *   PAYPAL_SANDBOX           - "true" for sandbox mode (default true)
 *   COINGATE_API_TOKEN       - CoinGate crypto payment token
 *   PAYMENT_WEBHOOK_SECRET   - Secret for verifying incoming webhooks
 *   tronDepositAddress       - Server-validated TRX receiving address
 *   tronNetwork              - Network associated with the TRX receiving address
 */

const crypto = require("crypto");

const SUPPORTED_FIAT = ["USD", "EUR", "GBP", "AED", "AUD", "CAD", "JPY", "CHF"];
const SUPPORTED_CRYPTO_PAY = ["BTC", "ETH", "USDT", "BNB", "SOL", "TRX", "ATX"];
// Static mock conversion rates used only for sandbox payment previews.
const MOCK_CRYPTO_RATES = { BTC: 65000, ETH: 3200, USDT: 1, BNB: 580, SOL: 160, TRX: 0.12, ATX: 0.05 };
const SUPPORTED_METHODS = [
  "card",
  "bank_transfer",
  "paypal",
  "crypto",
  "apple_pay",
  "google_pay",
  "sepa",
  "wire",
];

class PaymentGatewayService {
  constructor(config = {}) {
    this.stripeKey = config.stripeKey || process.env.STRIPE_SECRET_KEY || null;
    this.paypalClientId = config.paypalClientId || process.env.PAYPAL_CLIENT_ID || null;
    this.paypalSecret = config.paypalSecret || process.env.PAYPAL_CLIENT_SECRET || null;
    this.paypalSandbox = (config.paypalSandbox ?? process.env.PAYPAL_SANDBOX) !== "false";
    this.coingateToken = config.coingateToken || process.env.COINGATE_API_TOKEN || null;
    this.tronDepositAddress = String(config.tronDepositAddress || "").trim() || null;
    this.tronNetwork = String(config.tronNetwork || "mainnet").trim().toLowerCase();
    this.autoGeneratedWebhookSecret = !config.webhookSecret && !process.env.PAYMENT_WEBHOOK_SECRET;
    this.webhookSecret =
      config.webhookSecret ||
      process.env.PAYMENT_WEBHOOK_SECRET ||
      crypto.randomBytes(16).toString("hex");
    this.mockMode = !this.stripeKey && !this.paypalClientId && !this.coingateToken;

    if (this.mockMode) {
      console.log("ℹ PaymentGatewayService running in mock/sandbox mode (no API keys configured)");
    }
    if (this.autoGeneratedWebhookSecret) {
      console.warn("⚠ PaymentGatewayService auto-generated PAYMENT_WEBHOOK_SECRET; webhook verification is disabled until configured");
    }
  }

  /** Generate a unique payment reference */
  _ref(prefix = "PAY") {
    return `${prefix}_${Date.now()}_${crypto.randomBytes(4).toString("hex").toUpperCase()}`;
  }

  /** Validate common payment fields */
  _validate({ amount, currency, method }) {
    if (!amount || isNaN(Number(amount)) || Number(amount) <= 0) throw new Error("Invalid amount");
    if (!currency || !SUPPORTED_FIAT.includes(currency.toUpperCase())) {
      throw new Error(`Unsupported currency: ${currency}`);
    }
    if (!method || !SUPPORTED_METHODS.includes(method)) throw new Error(`Unsupported method: ${method}`);
  }

  /** Create a payment intent/order */
  async createPayment({ amount, currency, method, metadata = {} }) {
    this._validate({ amount, currency, method });
    const ref = this._ref("PAY");
    const now = new Date().toISOString();

    if (this.mockMode) {
      return {
        id: ref,
        status: "pending",
        method,
        amount: Number(amount),
        currency: currency.toUpperCase(),
        createdAt: now,
        expiresAt: new Date(Date.now() + 30 * 60 * 1000).toISOString(),
        checkoutUrl: null,
        qrData: method === "crypto" ? `crypto:${ref}?amount=${amount}` : null,
        instructions: this._getInstructions(method, amount, currency),
        metadata,
        mock: true,
      };
    }

    // Real integrations (Stripe, PayPal) would go here
    throw new Error("Live payment processing requires API keys configured in .env");
  }

  /** Process a crypto payment address request */
  async createCryptoPayment({
    amount,
    currency,
    cryptoAmount: requestedCryptoAmount,
    cryptoSymbol,
    metadata = {},
  }) {
    const symbol = (cryptoSymbol || "").toUpperCase();
    if (!SUPPORTED_CRYPTO_PAY.includes(symbol)) {
      throw new Error(`Unsupported crypto: ${cryptoSymbol}`);
    }
    const address = symbol === "TRX" ? this.tronDepositAddress : this._mockAddress(symbol);
    if (!address) {
      throw new Error(`TRX receiving wallet is not configured for ${this.tronNetwork}`);
    }

    const ref = this._ref("CPAY");
    const cryptoAmount =
      symbol === "TRX"
        ? this._normalizeTrxAmount(requestedCryptoAmount)
        : (Number(amount) / (MOCK_CRYPTO_RATES[symbol] || 1)).toFixed(8);

    return {
      id: ref,
      status: "awaiting_payment",
      fiatAmount: Number(amount),
      fiatCurrency: currency.toUpperCase(),
      cryptoAmount,
      cryptoSymbol: symbol,
      address,
      qrData: `${symbol.toLowerCase()}:${address}?amount=${cryptoAmount}`,
      network: symbol === "TRX" ? this.tronNetwork : null,
      autoCredit: false,
      quoteMode: symbol === "TRX" ? "manual" : "sandbox",
      expiresAt: new Date(Date.now() + 15 * 60 * 1000).toISOString(),
      metadata,
      mock: true,
    };
  }

  /** Refund a payment */
  async refundPayment({ paymentId, amount, reason = "customer_request" }) {
    if (!paymentId) throw new Error("paymentId required");
    const ref = this._ref("REF");
    return {
      id: ref,
      paymentId,
      amount: Number(amount) || null,
      reason,
      status: "refunded",
      processedAt: new Date().toISOString(),
      mock: true,
    };
  }

  /** Verify a webhook signature */
  verifyWebhook(payload, signature) {
    if (this.autoGeneratedWebhookSecret) {
      return false;
    }
    const computed = crypto
      .createHmac("sha256", this.webhookSecret)
      .update(payload)
      .digest("hex");
    const normalizedSignature = String(signature || "").trim().toLowerCase();
    if (!/^[a-f0-9]{64}$/.test(normalizedSignature)) {
      return false;
    }
    const computedBuffer = Buffer.from(computed, "hex");
    const signatureBuffer = Buffer.from(normalizedSignature, "hex");
    if (computedBuffer.length !== signatureBuffer.length) {
      return false;
    }
    return crypto.timingSafeEqual(computedBuffer, signatureBuffer);
  }

  /** Get supported methods */
  getSupportedMethods() {
    return {
      methods: SUPPORTED_METHODS,
      fiatCurrencies: SUPPORTED_FIAT,
      cryptoCurrencies: SUPPORTED_CRYPTO_PAY,
      mockMode: this.mockMode,
    };
  }

  _getInstructions(method, amount, currency) {
    const map = {
      card: `Enter your card details to pay ${amount} ${currency}`,
      bank_transfer: `Transfer ${amount} ${currency} to account details shown below`,
      paypal: `You will be redirected to PayPal to complete the ${amount} ${currency} payment`,
      crypto: "Send the exact crypto amount to the address provided",
      apple_pay: `Use Apple Pay to pay ${amount} ${currency}`,
      google_pay: `Use Google Pay to pay ${amount} ${currency}`,
      sepa: `SEPA direct debit of ${amount} ${currency} will be initiated`,
      wire: `Wire transfer of ${amount} ${currency} — allow 1-3 business days`,
    };
    return map[method] || `Pay ${amount} ${currency}`;
  }

  _normalizeTrxAmount(amount) {
    const value = String(amount ?? "").trim();
    if (
      !/^(?:0|[1-9]\d{0,11})(?:\.\d{1,6})?$/.test(value) ||
      Number(value) <= 0
    ) {
      throw new Error("TRX amount must be positive and use no more than 6 decimal places");
    }
    return value;
  }

  _mockAddress(symbol) {
    const prefixes = { BTC: "1", ETH: "0x", BNB: "bnb", SOL: "", TRX: "T", USDT: "0x", ATX: "0x" };
    const prefix = prefixes[symbol.toUpperCase()] || "0x";
    return `${prefix}${crypto.randomBytes(20).toString("hex")}`;
  }
}

module.exports = PaymentGatewayService;
